x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae07,uclvlddpragae08,api,web,baserow,redis,celery_worker

x-proxy-common: &proxy-common
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

x-build-args-common: &build-args-common
  <<: *proxy-common
  HYLODE_UID: ${HYLODE_UID}

x-celery-args-common: &celery-args-common
  <<: *build-args-common
  CELERY_DASH_BROKER_URL: redis://:${REDIS_PASSWORD}@localhost:6379/0
  CELERY_DASH_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@localhost:6379/0

x-web-args-common: &web-args-common
  << : *build-args-common
  WEB_CELERY_DASH_BROKER_URL: redis://:${REDIS_PASSWORD}@localhost:6379/0
  WEB_CELERY_DASH_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@localhost:6379/0
  WEB_REDIS_CACHE: redis://:${REDIS_PASSWORD}@localhost:6379/1


services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
    env_file: .env.dev
    ports:
      - ${API_PORT}:8000
    networks:
      - hyui

  web:
    build:
      dockerfile: docker/web/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: [*proxy-common, *web-args-common]
    # Using differnt environment variables
    env_file: .env.dev
    ports:
      - ${WEB_PORT}:8000 # switch from 8000 (exposed by gunicorn + app.server) to 8300 which is the dev port
      - 10001:10001 # port on which debug.py listens
    # add in a volumes section
    volumes:
    # attach as bind mounts so you can edit the code whilst the container still runs
      - ./web/src/web:/app/web
      - ./models/src/models:/app/models
    depends_on:
      - baserow
      - api
      - redis
    networks:
      - hyui

  redis:
    image: redis:7.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      <<: *proxy-common
    ports:
      - 6379:6379
    networks:
      - hyui

  redisinsight:
    image: redislabs/redisinsight
    environment:
      <<: *proxy-common
    ports:
      - 8309:8001
    depends_on:
      - redis
    volumes:
      - redisinsight:/db
    networks:
      - hyui

  celery_worker:
    build:
      dockerfile: docker/celery/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: [*proxy-common, *celery-args-common]
    #  mount code directly for development but COPY in production
    #  (hence delete these lines)
    volumes:
      - ./web/src/web:/app/web
      - ./models/src/models:/app/models
    command: /app/start-worker
    env_file:
      - .env.dev
    depends_on:
      - redis
    networks:
      - hyui

  celery_beat:
    build:
      dockerfile: docker/celery/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: [*proxy-common, *celery-args-common]
    command: /app/start-beat
    env_file:
      - .env.dev
    depends_on:
      - redis
    networks:
      - hyui


  celery_flower:
    build:
      dockerfile: docker/celery/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: [*proxy-common, *celery-args-common]
    command: /app/start-flower
    ports:
      - "${FLOWER_PORT}:5557"
    env_file:
      - .env.dev
    depends_on:
      - redis
      - celery_worker
    networks:
      - hyui

  baserow:
    image: baserow/baserow:1.16.0
    environment:
      <<: *proxy-common
    env_file: .env.dev
    ports:
      - ${BASEROW_PORT}:80
      - 8443:443
    networks:
      - hyui
    volumes:
      - baserow-data:/baserow/data

networks:
  hyui:

volumes:
  baserow-data:
  redisinsight:
