{
 "title": "HyUI Status Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HyUI Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_com_docker_compose_project=\"hyui-staging\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time since container last seen",
   "type": "gauge",
   "description": "A proxy for uptime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{container_label_com_docker_compose_project=\"hyui-staging\"}) < 18000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container restarts in the last 5 minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (changes(container_start_time_seconds{container_label_com_docker_compose_project=\"hyui-staging\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}